CREATE DATABASE HEALTHCARE

USE HEALTHCARE

CREATE TABLE Employees(ID INT IDENTITY(1,1) PRIMARY KEY, Lname VARCHAR(20), Fname VARCHAR(20), Minitial VARCHAR(5), Hiredate DATE, Assclinic VARCHAR(50))
CREATE TABLE Skills(ID INT IDENTITY(1,1) PRIMARY KEY, Description VARCHAR(200), Hourlyrate DECIMAL(16,2), EID INT FOREIGN KEY REFERENCES Employees(ID))
CREATE TABLE Clinics(ID INT IDENTITY(1,1) PRIMARY KEY, Name VARCHAR(20), Location VARCHAR(20), Contact VARCHAR(15))
CREATE TABLE Patients(ID INT IDENTITY(1,1) PRIMARY KEY, Name VARCHAR(20), DOB DATE, Contact VARCHAR(15), CID INT FOREIGN KEY REFERENCES Clinics(ID))
CREATE TABLE Appointments(ID INT IDENTITY(1,1) PRIMARY KEY, Date DATE, Time DATETIME, Reason VARCHAR(200), Consroom VARCHAR(20), PID INT FOREIGN KEY REFERENCES Patients(ID), EID INT FOREIGN KEY REFERENCES Employees(ID))
CREATE TABLE Projects(ID INT IDENTITY(1,1) PRIMARY KEY, Description VARCHAR(200), Startdate DATE, Enddate DATE, Budget DECIMAL(16,2), Actualcost DECIMAL(16,2), EID INT FOREIGN KEY REFERENCES Employees(ID))
CREATE TABLE Tasks(ID INT IDENTITY(1,1) PRIMARY KEY, Description VARCHAR(200), Startdate DATE, Enddate DATE, Noofemployees INT, SID INT FOREIGN KEY REFERENCES Skills(ID))
CREATE TABLE Assignments(ID INT IDENTITY(1,1) PRIMARY KEY, Startdate DATE, Enddate DATE, Hours VARCHAR(10))
CREATE TABLE Worklogs(ID INT IDENTITY(1,1) PRIMARY KEY, Date DATE, Hours VARCHAR(10), TID INT FOREIGN KEY REFERENCES Tasks(ID), AID INT FOREIGN KEY REFERENCES Assignments(ID))
CREATE TABLE Billing(Billno INT IDENTITY(1,1) PRIMARY KEY, Date DATE, Total DECIMAL(16,2), WID INT FOREIGN KEY REFERENCES Worklogs(ID))

